version: '3'
services:
  loon:
    image: loon:latest
    links:
      - redis
    command:
      pytest loonfilter/test_loon.py

  redis:
    restart: unless-stopped
    image: redis:4.0.9-alpine
    ports:
      - 6379:6379
