version: '3'
services:
  larkspur:
    image: larkspur:latest
    links:
      - redis
    command:
      pytest larkspur/test_larkspur.py

  redis:
    restart: unless-stopped
    image: redis:4.0.9-alpine
    ports:
      - 6379:6379
